name: drucal
recipe: drupal10
config:
  php: '8.2'
services:
  appserver:
    webroot: web
    xdebug: debug
    config:
      php: .vscode/php.ini
    overrides:
      environment:
        SIMPLETEST_BASE_URL: "http://drucal.lndo.site"
        SIMPLETEST_DB: "sqlite://localhost/sites/default/files/db.sqlite"
    build_as_root:
      - apt-get update && apt-get install -y libtidy-dev && docker-php-ext-install tidy && docker-php-ext-enable tidy
tooling:
  test:
    service: appserver
    cmd: "php /app/vendor/bin/phpunit -c /app/phpunit.xml"
